project:
  type: website
mainfont: "Atkinson Hyperlegible"


website:
  title: "LittleMonkeyLab"

  description: "Our Lab Website"
  site-url: https://www.littlemonkeylab.com
  repo-url: https://github.com/littlemonkeylab/LabWebsite
  sidebar:
    style: docked
    logo: images/LMLLOGO.png
    collapse-level: 1
    header: "LittleMonkeyLab"
    footer: "[Email List Sign-up](http://eepurl.com/gBI-qz)"

  open-graph: true
  favicon: favicon.png
  twitter-card:
    creator: "@littlemonkeylab"
    site: "@littlemonkeylab"
    card-style: "summary_large_image"
  navbar:
    background: "#003366"
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Dr.Gordon Wright
      - href: team.qmd
        text: TheMonkeys
    right:
    - icon: twitter
      href: https://twitter.com/littlemonkeylab
    - icon: github
      href: https://github.com/littlemonkeylab
  page-navigation: true
  page-footer:
    center: "Made with 💛 and Quarto.   [Email List Sign-up](http://eepurl.com/gBI-qz)    Copyright © 2022 Dr. Gordon Wright"
    background: "#003366"
    foreground: "white"
format:
  html:
    theme: cosmo
    css: website.css
    mainfont: "Atkinson Hyperlegible"
    sansfont: "Atkinson Hyperlegible"
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    include-in-header:
      - includes.html
    highlight-style: tango
