project:
  type: website
  output-dir: _site

website:
  title: "LittleMonkeyLab"
  description: "Our Lab Website"
  site-url: https://www.littlemonkeylab.com
  repo-url: https://github.com/littlemonkeylab/LabWebsite

  open-graph: true
  favicon: favicon.png
  twitter-card: 
    creator: "@littlemonkeylab"
    site: "@littlemonkeylab"
    card-style: "summary_large_image"
  navbar:
    background: "yellow"
    foreground: dark
    left:
      - href: index.qmd
        text: Home
    right: 
    - icon: twitter
      href: https://twitter.com/littlemonkeylab
    - icon: linkedin
      href: https://www.linkedin.com/in/gordonrtwright
    - icon: github
      href: https://github.com/littlemonkeylab
  page-navigation: true
  page-footer: 
    center: "Copyright © 2022 Dr. Gordon Wright"
    background: primary
    foreground: "white"
format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    include-in-header:
      - includes.html
    highlight-style: tango
