---
title: "Dr. Gordon Wright"
---

It's all pretty busy these days!

### Research Interests

-   Deception (Lie detection and lie production)
-   Aversive (dark) personality traits (Machiavellianism, Psychopathy,
    Narcissism & Sadism)
-   Interpersonal interaction
-   Interpersonal perception and behaviour prediction
-   Data Science
-   Experimental Design

### Doctoral Research

::: {.d-flex .justify-content-between}
<div>

**Birkbeck, University of London**\
PhD in Experimental Psychology

Supervisors: Professor Geoff Bird, Professor Anne Richards, Dr. Clare
Press

</div>

::: text-end
London 2014
:::
:::

-   Dissertation: *Deception General Ability: Individual differences in
    the ability to lie and to detect deception* (ESRC funded)

### Employment

::: {.d-flex .justify-content-between}
<div>

**Goldsmiths, University of London**\
Lecturer in Psychology

</div>

::: text-end
London, UK\
Started 2016
:::
:::

### Teaching

#### Undergraduate Research Methods Y2 (Level 5)

+-----------------+----------------------------------------------------+
| Year            | Teaching                                           |
+=================+====================================================+
| Current         | Research Methods in Psychology (Y2) - Module       |
|                 | Coordinator and Principle Lecturer                 |
|                 |                                                    |
|                 | Psychology and Law (Y3) - Lecturer                 |
+-----------------+----------------------------------------------------+
| 2017 - 2022     | Psychology and Law (Y3) - Module Coordinator and   |
|                 | co-lecturer                                        |
+-----------------+----------------------------------------------------+
|                 |                                                    |
+-----------------+----------------------------------------------------+

<!-- ::: {.d-flex .justify-content-between} -->

<!-- ::: {} -->

<!-- Introduction to R for NYU Datalab -->

<!-- ::: -->

<!-- ::: {.text-end} -->

<!-- January 2013 -->

<!-- ::: -->

<!-- ::: -->
